In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [4]:
from collections import Counter
s = 'hello'
hello = Counter(s)
print(hello)

Counter({'l': 2, 'h': 1, 'e': 1, 'o': 1})


In [43]:
from tensorflow.keras.utils import to_categorical
x1,x2,x3,x4,x5 = to_categorical([0,1,2,2,3]).reshape(5,4,1)

In [44]:
np.hstack((x1,x2,x3,x4,x5))

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 1., 0.],
       [0., 0., 0., 0., 1.]], dtype=float32)

### Karpathy 예제

In [ ]:
# # Data I/O
# data = open('no_such_thing.txt', 'r').read()
# data = ' '.join(data.split('\n'))
# data = ''.join(data.split('"'))
# chars = list(set(data.lower()))
# data_size, vocab_size = len(data), len(chars)
# print('data has {} characters, {} uniques'.format(data_size, vocab_size))
# char_to_ix = { ch:i for i,ch in enumerate(chars) }
# ix_to_char = { i:ch for i,ch in enumerate(chars) }

In [45]:
# hyperparameter
hidden_size = 3 # size of hiddne layer of neurons
# seq_length = 25 # number of steps to unroll the RNN for
# learing_rate = 1e-1

In [46]:
vocab_size = len(x1) # length of one-hot encoding vector
# model parameters
Wxh = np.random.randn(hidden_size, vocab_size)*0.01 # input to hidden
Whh = np.random.randn(hidden_size, hidden_size)*0.01 # hidden to hidden
Why = np.random.randn(vocab_size, hidden_size)*0.01 # hidden to output
bh = np.zeros((hidden_size, 1)) # hidden bias
by = np.zeros((vocab_size, 1)) # output bias

Wxh.shape, Whh.shape, Why.shape, bh.shape, by.shape

((3, 4), (3, 3), (4, 3), (3, 1), (4, 1))

$$h_t=\text{tanh}(W_{hh}h_{t-1}+W_{xh}x_t)$$
$$y_t=W_{hy}h_t$$

In [63]:
Whh = np.ones((3,3))
Wxh = np.ones((3,4))
Why = np.tile(np.array([1,0,2,3], dtype=np.float32).reshape(-1,1), 3)
print(Whh, '\n\n', Wxh, '\n\n', Why)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]] 

 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]] 

 [[1. 1. 1.]
 [0. 0. 0.]
 [2. 2. 2.]
 [3. 3. 3.]]


In [80]:
# h0 = np.zeros((hidden_size, 1)) # reset RNN Memory
h1 = np.tanh(np.dot(Whh, h0) + np.dot(Wxh, x1) + bh)
y1 = np.dot(Why, h1) + by
print(h1, '\n\n', y1)

[[0.76159416]
 [0.76159416]
 [0.76159416]] 

 [[2.28478247]
 [0.        ]
 [4.56956494]
 [6.8543474 ]]


In [193]:
p = np.exp(y1) / np.sum(np.exp(y1))
ix = np.random.choice(list(range(vocab_size)), p=p.ravel()) # 결과값에서 어떤 것을 선택할지는 프로그래머의 마음
p

array([[0.00930861],
       [0.00094758],
       [0.09144356],
       [0.89830026]])

In [194]:
ix = 2 # index 2가 9%의 확률로 뽑혔다고 가정

In [195]:
x = np.zeros((vocab_size, 1))
x[ix] = 1
x

array([[0.],
       [0.],
       [1.],
       [0.]])

In [196]:
h2 = np.tanh(np.dot(Whh, h1) + np.dot(Wxh, x) + bh)
y2 = np.dot(Why, h2) + by
print(h2, '\n\n', y2)

[[0.99719911]
 [0.99719911]
 [0.99719911]] 

 [[2.99159734]
 [0.        ]
 [5.98319468]
 [8.97479202]]


In [203]:
p = np.exp(y2) / np.sum(np.exp(y2))
ix = np.random.choice(list(range(vocab_size)), p=p.ravel()) # 결과값에서 어떤 것을 선택할지는 프로그래머의 마음
p, ix

(array([[2.39421535e-03],
        [1.20206788e-04],
        [4.76867174e-02],
        [9.49798861e-01]]), 3)

In [204]:
x = np.zeros((vocab_size, 1))
x[ix] = 1
x

array([[0.],
       [0.],
       [0.],
       [1.]])

In [205]:
h3 = np.tanh(np.dot(Whh, h2) + np.dot(Wxh, x) + bh)
y3 = np.dot(Why, h3) + by
print(h3, '\n\n', y3)

[[0.99931794]
 [0.99931794]
 [0.99931794]] 

 [[2.99795381]
 [0.        ]
 [5.99590762]
 [8.99386143]]


In [206]:
p = np.exp(y3) / np.sum(np.exp(y3))
ix = np.random.choice(list(range(vocab_size)), p=p.ravel()) # 결과값에서 어떤 것을 선택할지는 프로그래머의 마음
p, ix

(array([[2.36476191e-03],
        [1.17975717e-04],
        [4.74004231e-02],
        [9.50116839e-01]]), 3)

In [207]:
x = np.zeros((vocab_size, 1))
x[ix] = 1
x

array([[0.],
       [0.],
       [0.],
       [1.]])

In [208]:
h4 = np.tanh(np.dot(Whh, h3) + np.dot(Wxh, x) + bh)
y4 = np.dot(Why, h4) + by
print(h4, '\n\n', y4)
p = np.exp(y4) / np.sum(np.exp(y4))
ix = np.random.choice(list(range(vocab_size)), p=p.ravel()) # 결과값에서 어떤 것을 선택할지는 프로그래머의 마음
p, ix

[[0.99932655]
 [0.99932655]
 [0.99932655]] 

 [[2.99797965]
 [0.        ]
 [5.9959593 ]
 [8.99393895]]


(array([[2.36464291e-03],
        [1.17966732e-04],
        [4.73992626e-02],
        [9.50118128e-01]]), 3)

In [209]:
x = np.zeros((vocab_size, 1))
x[ix] = 1
x

array([[0.],
       [0.],
       [0.],
       [1.]])

- 뽑힌 단어는 hlooo
- 제대로 학습시킨다면 hello를 출력시킬 수 있다.

$$h_t=\text{tanh}(W_{hh}h_{t-1}+W_{xh}x_t+b_h)$$
$$y_t=W_{hy}h_t+b_y$$

- https://gist.github.com/karpathy/d4dee566867f8291f086

In [211]:
def sample(h, seed_ix, n):
    x = np.zeros((vocab_size, 1))
    x[seed_ix] = 1
    ixes = []
    for t in range(n):
        h = np.tanh(np.dot(Whh, h) + np.dot(Wxh, x) + bh)
        y = np.dot(Why, h) + by
        p = np.exp(y) / np.sum(np.exp(y))
        ix = np.random.choice(list(range(vocab_size)), p=p.ravel())
        x = np.zeros((vocab_size, 1))
        x[ix] = 1
        ixes.append(ix)
    return ixes

```python
[char_to_ix[ch] for ch in data.lower()[0:10]] # inputs
[char_to_ix[ch] for ch in data.lower()[0+1:10+1]] # targets
```

In [226]:
(1 / (1 + np.exp(np.array([2.,1.,.1])))) / np.sum(1 / (1 + np.exp(np.array([2.,1.,.1]))))

array([0.13809978, 0.31157585, 0.55032436])

- $\text{tanh}(x)$의 미분
$$\dfrac{d}{dx}\text{tanh}(x)=1-\text{tanh}^2(x)$$

In [240]:
def lossFun(inputs, targets, hprev):
    xs, hs, ys, ps = {}, {}, {}, {}
    hs[-1] = np.copy(hprev)
    loss = 0
    # forward pass
    for t in range(len(inputs)):
        xs[t] = np.zeros((vocab_size, 1)) # encode in 1-of-k representation
        xs[t][inputs[t]] = 1
        hs[t] = np.tanh(np.dot(Wxh, xs[t]) + np.dot(Whh, hs[t-1]) + bh) # hidden layer
        ys[t] = np.dot(Why, hs[t]) + by # unnormalized log probabilities for next chars
        ps[t] = np.exp(ys[t]) / np.sum(np.exp(ys[t])) # probabilities for next chars
        loss += -np.log(ps[t][targets[t], 0]) # softmax (cross-entropy Loss)
    # backward pass : compute gradients going backwards
    dWxh, dWhh, dWhy = np.zeros_like(Wxh), np.zeros_like(Whh), np.zeros_like(Why)
    dbh, dby = np.zeros_like(bh), np.zeros_like(by)
    dhnext = np.zeros_like(hs[0])
    for t in reversed(range(len(inputs))):
        dy = np.copy(ps[t])
        dy[targets[t]] -= -1 # backprop into y
                             # see http://cs231n.github.io/neural-networks-case-study/#grad if confused here
        dWhy += np.dot(dy, hs[t].T) # (vocab_size, 1) x (hidden_size, 1).T = (vocab_size, hidden_size)
        dby += dy # add prop => 그대로
        dh = np.dot(Why.T, dy) + dhnext # backprop into h
                                        # (vocab_size, hidden_size).T x (vocab_size, 1) + (hidden_size, 1)
                                        # 거꾸로 실행되기 대문에 h_t의 경우 역전파가 남아있음. dhnext를 더해준다.
        dhraw = (1 - hs[t] * hs[t]) * dh # (hidden_size, 1)
                                         # backprop through tanh nonlinearity
        dbh += dhraw # add prop => 그대로
        dWxh += np.dot(dhraw, xs[t].T) # (hidden_size, 1) x (vocab_size, 1).T
        dWhh += np.dot(dhraw, hs[t].T) # (hidden_size, 1) x (hidden_size, 1).T
        dhnext = np.dot(Whh.T, dhraw) # (hidden_size, hidden_size).T x (hidden_size, 1)
    for dparam in [dWxh, dWhh, dWhy, dbh, dby]:
        np.clip(dparam, -5, 5, out=dparams) # clip to mitigate exploding gradients
    return loss, dWxh, dWhh, dWhy, dbh, dby, hs[len(inputs) - 1]

`np.clip`
- https://rfriend.tistory.com/tag/np.clip%28%29

In [239]:
a = np.arange(10) # Clip (limit) the values in an array.
np.clip(a, 2, 7)
print(a)
np.clip(a, 2, 7, out=a)
print(a)

[0 1 2 3 4 5 6 7 8 9]
[2 2 2 3 4 5 6 7 7 7]


- Vanilla RNN에서 Vanishing Gradient 문제를 어떻게 해결할 것인가?
- 200글자의 backprop을 모두 구한다면 상당한 어려움이 존재할 것
- 이를 위해 분리된 Backprop (Truncated Backpropagation Through Time - BPTT)를 사용
    - sequence length로 정해 놓은 변수 길이에 맞춰서 자르고
    - 다음 step에서는 또 sequence length만큼 잘라서 학습