In [13]:
import numpy as np

y = np.random.randint(0, 2, 40)
y

array([1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1,
       1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1])

In [14]:
np.atleast_1d(y)
# Convert inputs to arrays with at least one dimension.

# Scalar inputs are converted to 1-dimensional arrays, whilst
# higher-dimensional inputs are preserved.

array([1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1,
       1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1])

In [15]:
if y.ndim == 1:
    # reshape is necessary to preserve the data contiguity against vs
    # [:, np.newaxis] that does not.
    y = np.reshape(y, (-1, 1))
y

array([[1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1]])

In [16]:
y_encoded = np.zeros(y.shape, dtype=np.int)
y_encoded

array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0]])

In [19]:
n_outputs_ = y.shape[1]
for k in range(n_outputs_):
    classes_k, y_encoded[:, k] = np.unique(y[:, k],
                                           return_inverse=True)

In [23]:
y = y_encoded

In [24]:
getattr(y, "dtype", None)

dtype('int32')

In [25]:
y.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [26]:
y.flags.contiguous

True

In [27]:
if getattr(y, "dtype", None) != DOUBLE or not y.flags.contiguous:
    y = np.ascontiguousarray(y, dtype=DOUBLE)

NameError: name 'DOUBLE' is not defined